version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost --silent" ]
      interval: 30s
      timeout: 30s
      retries: 3
  redis:
    image: redis:7.4.0
    ports:
      - $SPRING_REDIS_PORT:$SPRING_REDIS_DOCKER_PORT
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 3
  frontend:
    build: .
    ports:
      - "3000:3000"

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: 0z10ne/hike-track
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "$MYSQLDB_USER"
      SPRING_DATASOURCE_PASSWORD: "$MYSQLDB_PASSWORD"

